version: '3'

services:
  cryptic-world:
    image: localhost:56151/cryptic-world
    build:
      context: ../../../
      dockerfile: Challenges/Web/cryptic-world/Dockerfile
    networks:
      nw0:
    deploy:
      resources:
        limits:
          memory: 200m
          cpus: '0.1'

networks:
  nw0:
    external: true
